{
  "inputs": [
    {
      "inputFile": "./environment-openapi-base-schema.json",
    },
    {
      "inputFile": "./schemas/ad/openapi.json",
      "pathModification": {
        "prepend": "/ad"
      },
      "dispute": {
        "prefix": "Ad"
      },
    },
    {
      "inputFile": "./schemas/friends/openapi.json",
      "pathModification": {
        "prepend": "/friends"
      },
      "dispute": {
        "prefix": "Friends"
      },
    },
    {
      "inputFile": "./schemas/settings/openapi.json",
      "pathModification": {
        "prepend": "/settings"
      },
      "dispute": {
        "prefix": "Settings"
      },
    },
    {
      "inputFile": "./schemas/users/openapi.json",
      "pathModification": {
        "prepend": "/users"
      },
      "dispute": {
        "prefix": "Users"
      },
    },
    {
      "inputFile": "./schemas/session/openapi.json",
      "pathModification": {
        "prepend": "/session"
      },
      "dispute": {
        "prefix": "Session"
      },
    },
    {
      "inputFile": "./schemas/inventory/openapi.json",
      "pathModification": {
        "prepend": "/inventory"
      },
      "dispute": {
        "prefix": "Inventory"
      },
    },
    {
      "inputFile": "./schemas/presence/openapi.json",
      "pathModification": {
        "prepend": "/presence"
      },
      "dispute": {
        "prefix": "Presence"
      },
    },
    {
      "inputFile": "./schemas/notification/openapi.json",
      "pathModification": {
        "prepend": "/notification"
      },
      "dispute": {
        "prefix": "Notification"
      },
    },
    {
      "inputFile": "./schemas/rank/openapi.json",
      "pathModification": {
        "prepend": "/rank"
      },
      "dispute": {
        "prefix": "Rank"
      },
    },
    {
      "inputFile": "./schemas/config/openapi.json",
      "pathModification": {
        "prepend": "/config"
      },
      "dispute": {
        "prefix": "Config"
      },
    },
  ],
  "output": "./openapi.json"
}
